### Assicurati che il server sia in esecuzione
@origin = https://localhost:7068

### Chiamata 1: Inizio della Partita
# @name startGame
POST {{origin}}/start
Content-Type: application/json

< ./Json/payload.json

### Separatore di Richiesta
###

### Chiamata 2: Prima Mossa
# @name firstMove
POST {{origin}}/move
Content-Type: application/json

< ./Json/payload.json
