<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TieredPGO>true</TieredPGO>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    </ItemGroup>

</Project>