<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TieredPGO>true</TieredPGO>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1"/>
        <PackageReference Include="Spectre.Console" Version="0.50.1-preview.0.26" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <_ContentIncludedByDefault Remove="publish\web.config"/>
        <_ContentIncludedByDefault Remove="publish\appsettings.json"/>
        <_ContentIncludedByDefault Remove="publish\Http\payload.json"/>
        <_ContentIncludedByDefault Remove="publish\Thanos.deps.json"/>
        <_ContentIncludedByDefault Remove="publish\Thanos.runtimeconfig.json"/>
        <_ContentIncludedByDefault Remove="publish\Thanos.staticwebassets.endpoints.json"/>
    </ItemGroup>

</Project>